name: cachebox
description: "Chat app with a shared webdrive."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_app_check: ^0.3.1

  # Core utilities
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  intl: ^0.20.2
  http: ^1.3.0
  path: ^1.9.1

  # File & media
  file_picker: ^8.3.5
  pdfx: ^2.8.0
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  # Add the native libs for the platforms you ship:
  media_kit_libs_android_video: ^1.3.7
  media_kit_libs_ios_video: ^1.1.4
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_linux: ^1.2.1   # optional: or rely on system libmpv

  # UI
  flutter_slidable: ^4.0.0
  flutter_highlight: ^0.7.0

  # Audio playback
  just_audio: ^0.10.1
  just_audio_background: ^0.0.1-beta.16

dependency_overrides:
  pdfx: 2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/cachebox_splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/cachebox_icon.png"

flutter:
  uses-material-design: true
