name: Upload APK to Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./cachebox.apk  # adjust if your APK is named differently
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
