name: Upload APK to GitHub Release

on:
  push:
    branches:
      - main

jobs:
  upload-release:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out code
        uses: actions/checkout@v3

      - name: 📦 Generate timestamped tag
        id: tagger
        run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_ENV"

      - name: 🚀 Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: CacheBox Release - ${{ env.TAG_NAME }}
          files: ./cachebox.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
